#!/usr/bin/env bash
# build_app.sh — assemble a minimal macOS .app bundle that launches the
# drive-xray Streamlit UI on double-click.
#
# Re-run after moving the project: the bundle hard-codes the project path.

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="drive-xray"
APP_DIR="${APP_DIR:-$HOME/Applications}"
APP_PATH="$APP_DIR/${APP_NAME}.app"
VERSION="0.1.0"

# Sanity: the venv must exist and contain streamlit. Without it the .app
# would fail silently on double-click.
VENV="$PROJECT_DIR/.venv"
if [[ ! -x "$VENV/bin/streamlit" ]]; then
    echo "error: $VENV/bin/streamlit not found." >&2
    echo "       run: python3 -m venv $VENV && $VENV/bin/pip install streamlit openpyxl plotly" >&2
    exit 1
fi
if [[ ! -f "$PROJECT_DIR/app.py" ]]; then
    echo "error: $PROJECT_DIR/app.py not found." >&2
    exit 1
fi

mkdir -p "$APP_DIR"
rm -rf "$APP_PATH"
mkdir -p "$APP_PATH/Contents/MacOS"
mkdir -p "$APP_PATH/Contents/Resources"

# ----- icon -----
# If assets/icon.png exists, build a multi-resolution .icns from it.
# Otherwise the .app uses the macOS default generic icon.
ICON_SRC="$PROJECT_DIR/assets/icon.png"
ICON_NAME=""
if [[ -f "$ICON_SRC" ]]; then
    echo "  building icns from $ICON_SRC..."
    ICONSET_DIR="$(mktemp -d)/AppIcon.iconset"
    mkdir -p "$ICONSET_DIR"
    # Apple's expected sizes for a complete iconset.
    declare -a SIZES=(16 32 64 128 256 512 1024)
    for s in "${SIZES[@]}"; do
        # 1x
        sips -z "$s" "$s" "$ICON_SRC" --out \
             "$ICONSET_DIR/icon_${s}x${s}.png" > /dev/null
        # 2x (skip 1024 — no 2048 expected)
        if [[ "$s" != "1024" ]]; then
            dbl=$((s * 2))
            sips -z "$dbl" "$dbl" "$ICON_SRC" --out \
                 "$ICONSET_DIR/icon_${s}x${s}@2x.png" > /dev/null
        fi
    done
    iconutil -c icns "$ICONSET_DIR" -o \
             "$APP_PATH/Contents/Resources/AppIcon.icns"
    rm -rf "$(dirname "$ICONSET_DIR")"
    ICON_NAME="AppIcon"
fi

# ----- Info.plist -----
cat > "$APP_PATH/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>           <string>${APP_NAME}</string>
    <key>CFBundleIdentifier</key>           <string>com.rleite.${APP_NAME}</string>
    <key>CFBundleName</key>                 <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>          <string>drive-xray</string>
    <key>CFBundlePackageType</key>          <string>APPL</string>
    <key>CFBundleVersion</key>              <string>${VERSION}</string>
    <key>CFBundleShortVersionString</key>   <string>${VERSION}</string>
    <key>CFBundleInfoDictionaryVersion</key><string>6.0</string>
$([ -n "$ICON_NAME" ] && echo "    <key>CFBundleIconFile</key>            <string>$ICON_NAME</string>")
    <key>LSMinimumSystemVersion</key>       <string>11.0</string>
    <key>LSUIElement</key>                  <false/>
    <key>NSHighResolutionCapable</key>      <true/>
    <key>NSPrincipalClass</key>             <string>NSApplication</string>
</dict>
</plist>
PLIST

# ----- launcher script -----
LAUNCHER="$APP_PATH/Contents/MacOS/${APP_NAME}"
cat > "$LAUNCHER" <<LAUNCH
#!/bin/bash
# drive-xray launcher — double-click entry point.
# Auto-generated by build_app.sh on $(date '+%Y-%m-%dT%H:%M:%S').

PROJECT="$PROJECT_DIR"
VENV="\$PROJECT/.venv"
APP_PY="\$PROJECT/app.py"
LOG_DIR="\$HOME/Library/Logs"
LOG="\$LOG_DIR/drive-xray.log"
PORT="\${DRIVE_XRAY_PORT:-8501}"

mkdir -p "\$LOG_DIR"
{
    echo
    echo "===== drive-xray starting at \$(date) ====="
    echo "  project: \$PROJECT"
} >> "\$LOG"

# If something basic is missing, show a real dialog instead of dying
# silently — the macOS Dock would otherwise just flash the icon.
err_dialog() {
    /usr/bin/osascript -e "display dialog \"\$1\" buttons {\"OK\"} default button \"OK\" with icon stop with title \"drive-xray\"" \\
        >> "\$LOG" 2>&1 || true
}

if [[ ! -x "\$VENV/bin/streamlit" ]]; then
    err_dialog "venv not found at \$VENV — run build_app.sh after creating it."
    exit 1
fi
if [[ ! -f "\$APP_PY" ]]; then
    err_dialog "app.py not found at \$APP_PY — re-run build_app.sh."
    exit 1
fi

# Find a free port if 8501 (or \$DRIVE_XRAY_PORT) is busy. Tries up to 10
# alternatives so multiple instances can coexist.
port_free() {
    ! /usr/sbin/lsof -i ":\$1" -sTCP:LISTEN > /dev/null 2>&1
}
for offset in 0 1 2 3 4 5 6 7 8 9; do
    CANDIDATE=\$((PORT + offset))
    if port_free "\$CANDIDATE"; then
        PORT="\$CANDIDATE"
        break
    fi
done
echo "  port:    \$PORT" >> "\$LOG"

# Hand off to Streamlit. Streamlit opens the browser itself.
exec "\$VENV/bin/streamlit" run "\$APP_PY" \\
    --server.port "\$PORT" \\
    --server.headless false \\
    --browser.gatherUsageStats false \\
    >> "\$LOG" 2>&1
LAUNCH
chmod +x "$LAUNCHER"

# ----- (icon handled above) -----

# Touch the bundle so Launch Services picks it up.
touch "$APP_PATH"
/usr/bin/touch "$APP_PATH"

cat <<DONE

✅ Built ${APP_NAME}.app

  Bundle:  $APP_PATH
  Logs:    ~/Library/Logs/drive-xray.log
  Launcher: $LAUNCHER

How to use:
  • Double-click the app in Finder → ~/Applications/${APP_NAME}.app
  • Or run from terminal:  open "$APP_PATH"
  • Or pin to Dock by dragging the .app icon onto the Dock.
  • To stop:  right-click the Dock icon → Quit. (Or click "X" on the
              browser tab and 'pkill -f streamlit' — Streamlit doesn't
              close itself when the browser closes.)

To use a different port (e.g. when 8501 is busy):
  DRIVE_XRAY_PORT=8888 open "$APP_PATH"

To rebuild after moving the project, re-run this script from inside the
project directory:
  bash build_app.sh

DONE
